// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: odo_error_func
 *
 * Args:
 *     t_i: Matrix31
 *     t_f: Matrix31
 *     t_odo: Matrix31
 *     s: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix31
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 3, 1> OdoErrorFunc(const Eigen::Matrix<Scalar, 3, 1>& t_i,
                                         const Eigen::Matrix<Scalar, 3, 1>& t_f,
                                         const Eigen::Matrix<Scalar, 3, 1>& t_odo, const Scalar s,
                                         const Scalar epsilon) {
  // Total ops: 9

  // Unused inputs
  (void)epsilon;

  // Input arrays

  // Intermediate terms (0)

  // Output terms (1)
  Eigen::Matrix<Scalar, 3, 1> _res;

  _res(0, 0) = -s * t_odo(0, 0) + t_f(0, 0) - t_i(0, 0);
  _res(1, 0) = -s * t_odo(1, 0) + t_f(1, 0) - t_i(1, 0);
  _res(2, 0) = -s * t_odo(2, 0) + t_f(2, 0) - t_i(2, 0);

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
