// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: odo_error_func_wrt_s
 *
 * Args:
 *     X_i: Matrix44
 *     X_f: Matrix44
 *     Rot_odo: Matrix33
 *     t_odo: Matrix31
 *     s: Scalar
 *
 * Outputs:
 *     res: Matrix61
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 1> OdoErrorFuncWrtS(const Eigen::Matrix<Scalar, 4, 4>& X_i,
                                             const Eigen::Matrix<Scalar, 4, 4>& X_f,
                                             const Eigen::Matrix<Scalar, 3, 3>& Rot_odo,
                                             const Eigen::Matrix<Scalar, 3, 1>& t_odo,
                                             const Scalar s) {
  // Total ops: 0

  // Unused inputs
  (void)X_i;
  (void)X_f;
  (void)Rot_odo;
  (void)t_odo;
  (void)s;

  // Input arrays

  // Intermediate terms (0)

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 1> _res;

  _res.setZero();

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
