// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: odo_error_func_wrt_pos_i
 *
 * Args:
 *     X_i: Matrix44
 *     X_f: Matrix44
 *     Rot_odo: Matrix33
 *     t_odo: Matrix31
 *     s: Scalar
 *
 * Outputs:
 *     res: Matrix6_16
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 6, 16> OdoErrorFuncWrtPosI(const Eigen::Matrix<Scalar, 4, 4>& X_i,
                                                 const Eigen::Matrix<Scalar, 4, 4>& X_f,
                                                 const Eigen::Matrix<Scalar, 3, 3>& Rot_odo,
                                                 const Eigen::Matrix<Scalar, 3, 1>& t_odo,
                                                 const Scalar s) {
  // Total ops: 2029

  // Unused inputs
  (void)Rot_odo;
  (void)t_odo;
  (void)s;

  // Input arrays

  // Intermediate terms (355)
  const Scalar _tmp0 = std::pow(X_i(0, 0), Scalar(-2));
  const Scalar _tmp1 = X_i(2, 0) * _tmp0;
  const Scalar _tmp2 = Scalar(1.0) / (X_i(0, 0));
  const Scalar _tmp3 = X_i(1, 0) * _tmp2;
  const Scalar _tmp4 = -X_i(0, 2) * _tmp3 + X_i(1, 2);
  const Scalar _tmp5 = X_i(1, 0) * _tmp0;
  const Scalar _tmp6 = X_i(2, 0) * _tmp2;
  const Scalar _tmp7 = -X_i(0, 1) * _tmp6 + X_i(2, 1);
  const Scalar _tmp8 = -X_i(0, 1) * _tmp3 + X_i(1, 1);
  const Scalar _tmp9 = std::pow(_tmp8, Scalar(-2));
  const Scalar _tmp10 = _tmp7 * _tmp9;
  const Scalar _tmp11 = X_i(0, 1) * _tmp10;
  const Scalar _tmp12 = _tmp11 * _tmp5;
  const Scalar _tmp13 = Scalar(1.0) / (_tmp8);
  const Scalar _tmp14 = X_i(0, 1) * _tmp13;
  const Scalar _tmp15 = _tmp1 * _tmp14;
  const Scalar _tmp16 = _tmp13 * _tmp7;
  const Scalar _tmp17 = _tmp16 * _tmp5;
  const Scalar _tmp18 = X_i(0, 2) * _tmp1 - X_i(0, 2) * _tmp17 + _tmp12 * _tmp4 - _tmp15 * _tmp4;
  const Scalar _tmp19 = X_i(0, 3) * _tmp2;
  const Scalar _tmp20 = -X_i(0, 3) * _tmp3 + X_i(1, 3);
  const Scalar _tmp21 = -X_i(2, 0) * _tmp19 + X_i(2, 3) - _tmp16 * _tmp20;
  const Scalar _tmp22 = _tmp16 * _tmp3 - _tmp6;
  const Scalar _tmp23 = X_i(0, 2) * _tmp2;
  const Scalar _tmp24 = _tmp16 * _tmp4;
  const Scalar _tmp25 = -X_i(2, 0) * _tmp23 + X_i(2, 2) - _tmp24;
  const Scalar _tmp26 = Scalar(1.0) / (_tmp25);
  const Scalar _tmp27 = X_i(3, 0) * _tmp2;
  const Scalar _tmp28 = -X_i(0, 1) * _tmp27 + X_i(3, 1);
  const Scalar _tmp29 = _tmp13 * _tmp28;
  const Scalar _tmp30 = -X_i(3, 0) * _tmp23 + X_i(3, 2) - _tmp29 * _tmp4;
  const Scalar _tmp31 = _tmp26 * _tmp30;
  const Scalar _tmp32 = -_tmp27 + _tmp29 * _tmp3;
  const Scalar _tmp33 = -_tmp22 * _tmp31 + _tmp32;
  const Scalar _tmp34 = _tmp21 * _tmp31;
  const Scalar _tmp35 = -X_i(3, 0) * _tmp19 + X_i(3, 3) - _tmp20 * _tmp29 - _tmp34;
  const Scalar _tmp36 = Scalar(1.0) / (_tmp35);
  const Scalar _tmp37 = _tmp33 * _tmp36;
  const Scalar _tmp38 = -_tmp21 * _tmp37 + _tmp22;
  const Scalar _tmp39 = std::pow(_tmp25, Scalar(-2));
  const Scalar _tmp40 = _tmp39 * _tmp4;
  const Scalar _tmp41 = _tmp38 * _tmp40;
  const Scalar _tmp42 = _tmp28 * _tmp9;
  const Scalar _tmp43 = X_i(0, 1) * _tmp42;
  const Scalar _tmp44 = std::pow(X_i(1, 0), Scalar(2));
  const Scalar _tmp45 = std::pow(X_i(0, 0), Scalar(-3));
  const Scalar _tmp46 = _tmp44 * _tmp45;
  const Scalar _tmp47 = _tmp30 * _tmp39;
  const Scalar _tmp48 = _tmp22 * _tmp47;
  const Scalar _tmp49 = X_i(3, 0) * _tmp0;
  const Scalar _tmp50 = _tmp14 * _tmp49;
  const Scalar _tmp51 = _tmp29 * _tmp5;
  const Scalar _tmp52 = _tmp43 * _tmp5;
  const Scalar _tmp53 =
      _tmp26 * (X_i(0, 2) * _tmp49 - X_i(0, 2) * _tmp51 - _tmp4 * _tmp50 + _tmp4 * _tmp52);
  const Scalar _tmp54 = X_i(1, 0) * _tmp14 * _tmp45;
  const Scalar _tmp55 = X_i(2, 0) * _tmp54 + _tmp1 - _tmp11 * _tmp46 - _tmp17;
  const Scalar _tmp56 = X_i(3, 0) * _tmp54 + _tmp18 * _tmp48 - _tmp22 * _tmp53 - _tmp31 * _tmp55 -
                        _tmp43 * _tmp46 + _tmp49 - _tmp51;
  const Scalar _tmp57 = _tmp21 * _tmp36;
  const Scalar _tmp58 = _tmp13 * _tmp20;
  const Scalar _tmp59 = X_i(0, 1) * _tmp58;
  const Scalar _tmp60 = _tmp20 * _tmp42;
  const Scalar _tmp61 = X_i(0, 1) * _tmp5;
  const Scalar _tmp62 = _tmp21 * _tmp47;
  const Scalar _tmp63 = X_i(0, 3) * _tmp1 - X_i(0, 3) * _tmp17 - _tmp1 * _tmp59 + _tmp12 * _tmp20;
  const Scalar _tmp64 = X_i(0, 3) * _tmp49 - X_i(0, 3) * _tmp51 + _tmp18 * _tmp62 -
                        _tmp21 * _tmp53 - _tmp31 * _tmp63 - _tmp49 * _tmp59 + _tmp60 * _tmp61;
  const Scalar _tmp65 = std::pow(_tmp35, Scalar(-2));
  const Scalar _tmp66 = _tmp33 * _tmp65;
  const Scalar _tmp67 = _tmp21 * _tmp66;
  const Scalar _tmp68 = -_tmp37 * _tmp63 + _tmp55 - _tmp56 * _tmp57 + _tmp64 * _tmp67;
  const Scalar _tmp69 = _tmp26 * _tmp4;
  const Scalar _tmp70 = _tmp20 * _tmp36;
  const Scalar _tmp71 = _tmp26 * _tmp38;
  const Scalar _tmp72 = X_i(0, 2) * _tmp71;
  const Scalar _tmp73 = _tmp20 * _tmp66;
  const Scalar _tmp74 = X_i(0, 3) * _tmp37;
  const Scalar _tmp75 = _tmp18 * _tmp41 - _tmp5 * _tmp72 - _tmp5 * _tmp74 + _tmp5 -
                        _tmp56 * _tmp70 + _tmp64 * _tmp73 - _tmp68 * _tmp69;
  const Scalar _tmp76 = X_f(0, 1) * _tmp13;
  const Scalar _tmp77 = X_f(0, 3) * _tmp66;
  const Scalar _tmp78 = X_f(0, 2) * _tmp26;
  const Scalar _tmp79 = _tmp36 * _tmp56;
  const Scalar _tmp80 = X_i(0, 3) * _tmp66;
  const Scalar _tmp81 = _tmp38 * _tmp39;
  const Scalar _tmp82 = X_i(0, 2) * _tmp81;
  const Scalar _tmp83 = X_i(0, 2) * _tmp26;
  const Scalar _tmp84 = X_i(0, 3) * _tmp36;
  const Scalar _tmp85 = _tmp20 * _tmp37;
  const Scalar _tmp86 = -_tmp3 - _tmp4 * _tmp71 - _tmp85;
  const Scalar _tmp87 = _tmp86 * _tmp9;
  const Scalar _tmp88 = std::pow(X_i(0, 1), Scalar(2));
  const Scalar _tmp89 = _tmp5 * _tmp88;
  const Scalar _tmp90 = -_tmp14 * _tmp75 + _tmp18 * _tmp82 - _tmp56 * _tmp84 + _tmp64 * _tmp80 -
                        _tmp68 * _tmp83 + _tmp87 * _tmp89;
  const Scalar _tmp91 = X_f(0, 0) * _tmp2;
  const Scalar _tmp92 = X_f(0, 2) * _tmp81;
  const Scalar _tmp93 = _tmp13 * _tmp86;
  const Scalar _tmp94 = _tmp0 * (-X_i(0, 1) * _tmp93 - _tmp72 - _tmp74 + 1);
  const Scalar _tmp95 = X_f(0, 1) * _tmp87;
  const Scalar _tmp96 = X_f(1, 2) * _tmp81;
  const Scalar _tmp97 = X_f(1, 1) * _tmp13;
  const Scalar _tmp98 = X_f(1, 2) * _tmp26;
  const Scalar _tmp99 = X_f(1, 3) * _tmp66;
  const Scalar _tmp100 = X_f(1, 0) * _tmp2;
  const Scalar _tmp101 = X_f(1, 1) * _tmp87;
  const Scalar _tmp102 = X_f(2, 2) * _tmp81;
  const Scalar _tmp103 = X_f(2, 1) * _tmp13;
  const Scalar _tmp104 = X_f(2, 2) * _tmp26;
  const Scalar _tmp105 = X_f(2, 3) * _tmp66;
  const Scalar _tmp106 = X_f(2, 0) * _tmp2;
  const Scalar _tmp107 = X_f(2, 1) * _tmp87;
  const Scalar _tmp108 = X_f(3, 2) * _tmp81;
  const Scalar _tmp109 = X_f(3, 1) * _tmp13;
  const Scalar _tmp110 = X_f(3, 3) * _tmp66;
  const Scalar _tmp111 = X_f(3, 2) * _tmp26;
  const Scalar _tmp112 = X_f(3, 0) * _tmp2;
  const Scalar _tmp113 = X_f(3, 1) * _tmp87;
  const Scalar _tmp114 = _tmp16 * _tmp31 - _tmp29;
  const Scalar _tmp115 = _tmp114 * _tmp65;
  const Scalar _tmp116 = X_f(0, 3) * _tmp115;
  const Scalar _tmp117 = _tmp114 * _tmp36;
  const Scalar _tmp118 = -_tmp117 * _tmp21 - _tmp16;
  const Scalar _tmp119 = _tmp118 * _tmp26;
  const Scalar _tmp120 = _tmp117 * _tmp20;
  const Scalar _tmp121 = -_tmp119 * _tmp4 - _tmp120 + 1;
  const Scalar _tmp122 = _tmp121 * _tmp13;
  const Scalar _tmp123 = X_i(0, 2) * _tmp119;
  const Scalar _tmp124 = X_i(0, 3) * _tmp117;
  const Scalar _tmp125 = _tmp0 * (-X_i(0, 1) * _tmp122 - _tmp123 - _tmp124);
  const Scalar _tmp126 = X_i(0, 3) * _tmp115;
  const Scalar _tmp127 = _tmp121 * _tmp9;
  const Scalar _tmp128 = _tmp16 * _tmp47;
  const Scalar _tmp129 = _tmp10 * _tmp31;
  const Scalar _tmp130 =
      -_tmp128 * _tmp18 - _tmp129 * _tmp61 + _tmp15 * _tmp31 + _tmp16 * _tmp53 - _tmp50 + _tmp52;
  const Scalar _tmp131 = _tmp130 * _tmp36;
  const Scalar _tmp132 = _tmp118 * _tmp39;
  const Scalar _tmp133 = X_i(0, 2) * _tmp132;
  const Scalar _tmp134 = _tmp115 * _tmp21;
  const Scalar _tmp135 = -_tmp117 * _tmp63 + _tmp12 - _tmp130 * _tmp57 + _tmp134 * _tmp64 - _tmp15;
  const Scalar _tmp136 = _tmp20 * _tmp65;
  const Scalar _tmp137 = _tmp114 * _tmp136;
  const Scalar _tmp138 = _tmp118 * _tmp40;
  const Scalar _tmp139 = -_tmp123 * _tmp5 - _tmp124 * _tmp5 - _tmp130 * _tmp70 - _tmp135 * _tmp69 +
                         _tmp137 * _tmp64 + _tmp138 * _tmp18;
  const Scalar _tmp140 = -X_i(0, 3) * _tmp131 + _tmp126 * _tmp64 + _tmp127 * _tmp89 +
                         _tmp133 * _tmp18 - _tmp135 * _tmp83 - _tmp139 * _tmp14;
  const Scalar _tmp141 = X_f(0, 2) * _tmp132;
  const Scalar _tmp142 = X_f(0, 1) * _tmp127;
  const Scalar _tmp143 = X_f(1, 1) * _tmp127;
  const Scalar _tmp144 = X_f(1, 3) * _tmp115;
  const Scalar _tmp145 = X_f(1, 2) * _tmp132;
  const Scalar _tmp146 = X_i(0, 1) * _tmp2;
  const Scalar _tmp147 = _tmp10 * _tmp146;
  const Scalar _tmp148 = -_tmp147 * _tmp4 + _tmp16 * _tmp23;
  const Scalar _tmp149 = _tmp12 + _tmp16 * _tmp2;
  const Scalar _tmp150 = _tmp146 * _tmp42;
  const Scalar _tmp151 = _tmp26 * (-_tmp150 * _tmp4 + _tmp23 * _tmp29);
  const Scalar _tmp152 =
      _tmp148 * _tmp48 - _tmp149 * _tmp31 - _tmp151 * _tmp22 + _tmp2 * _tmp29 + _tmp52;
  const Scalar _tmp153 = X_f(0, 3) * _tmp36;
  const Scalar _tmp154 = -_tmp147 * _tmp20 + _tmp16 * _tmp19;
  const Scalar _tmp155 =
      -_tmp146 * _tmp60 + _tmp148 * _tmp62 - _tmp151 * _tmp21 - _tmp154 * _tmp31 + _tmp19 * _tmp29;
  const Scalar _tmp156 = _tmp149 - _tmp152 * _tmp57 - _tmp154 * _tmp37 + _tmp155 * _tmp67;
  const Scalar _tmp157 = _tmp2 * _tmp88;
  const Scalar _tmp158 = -_tmp2;
  const Scalar _tmp159 = _tmp148 * _tmp41 - _tmp152 * _tmp70 + _tmp155 * _tmp73 - _tmp156 * _tmp69 +
                         _tmp158 + _tmp19 * _tmp37 + _tmp23 * _tmp71;
  const Scalar _tmp160 = -_tmp14 * _tmp159 + _tmp148 * _tmp82 - _tmp152 * _tmp84 +
                         _tmp155 * _tmp80 - _tmp156 * _tmp83 - _tmp157 * _tmp87;
  const Scalar _tmp161 = X_f(1, 3) * _tmp36;
  const Scalar _tmp162 = _tmp152 * _tmp36;
  const Scalar _tmp163 = -_tmp128 * _tmp148 + _tmp147 * _tmp31 - _tmp150 + _tmp151 * _tmp16;
  const Scalar _tmp164 = _tmp163 * _tmp36;
  const Scalar _tmp165 = -_tmp117 * _tmp154 + _tmp134 * _tmp155 - _tmp147 - _tmp163 * _tmp57;
  const Scalar _tmp166 = _tmp117 * _tmp19 + _tmp119 * _tmp23 + _tmp137 * _tmp155 +
                         _tmp138 * _tmp148 - _tmp163 * _tmp70 - _tmp165 * _tmp69;
  const Scalar _tmp167 = -X_i(0, 3) * _tmp164 + _tmp126 * _tmp155 - _tmp127 * _tmp157 +
                         _tmp133 * _tmp148 - _tmp14 * _tmp166 - _tmp165 * _tmp83;
  const Scalar _tmp168 = _tmp146 * _tmp58 - _tmp19;
  const Scalar _tmp169 = _tmp14 * _tmp2;
  const Scalar _tmp170 = _tmp169 * _tmp4 - _tmp23;
  const Scalar _tmp171 = -_tmp168 * _tmp31 + _tmp170 * _tmp62;
  const Scalar _tmp172 = -_tmp14 * _tmp5 + _tmp158;
  const Scalar _tmp173 = _tmp170 * _tmp48 - _tmp172 * _tmp31;
  const Scalar _tmp174 = -_tmp168 * _tmp37 + _tmp171 * _tmp67 + _tmp172 - _tmp173 * _tmp57;
  const Scalar _tmp175 = _tmp170 * _tmp41 + _tmp171 * _tmp73 - _tmp173 * _tmp70 - _tmp174 * _tmp69;
  const Scalar _tmp176 = _tmp2 * (-_tmp14 * _tmp175 + _tmp170 * _tmp82 + _tmp171 * _tmp80 -
                                  _tmp173 * _tmp84 - _tmp174 * _tmp83);
  const Scalar _tmp177 = _tmp173 * _tmp36;
  const Scalar _tmp178 = -_tmp128 * _tmp170 - _tmp169 * _tmp31;
  const Scalar _tmp179 = -_tmp117 * _tmp168 + _tmp134 * _tmp171 + _tmp169 - _tmp178 * _tmp57;
  const Scalar _tmp180 =
      _tmp137 * _tmp171 + _tmp138 * _tmp170 - _tmp178 * _tmp70 - _tmp179 * _tmp69;
  const Scalar _tmp181 = _tmp126 * _tmp171 + _tmp133 * _tmp170 - _tmp14 * _tmp180 -
                         _tmp178 * _tmp84 - _tmp179 * _tmp83;
  const Scalar _tmp182 = _tmp179 * _tmp26;
  const Scalar _tmp183 = _tmp170 * _tmp26;
  const Scalar _tmp184 = _tmp168 - _tmp183 * _tmp21;
  const Scalar _tmp185 = _tmp172 - _tmp183 * _tmp22;
  const Scalar _tmp186 = _tmp184 * _tmp67 - _tmp185 * _tmp57;
  const Scalar _tmp187 = _tmp184 * _tmp73 - _tmp185 * _tmp70 - _tmp186 * _tmp69;
  const Scalar _tmp188 = _tmp186 * _tmp26;
  const Scalar _tmp189 =
      -X_i(0, 2) * _tmp188 - _tmp14 * _tmp187 + _tmp184 * _tmp80 - _tmp185 * _tmp84;
  const Scalar _tmp190 = _tmp185 * _tmp36;
  const Scalar _tmp191 = _tmp16 * _tmp183 + _tmp169;
  const Scalar _tmp192 = _tmp134 * _tmp184 - _tmp191 * _tmp57;
  const Scalar _tmp193 = _tmp191 * _tmp36;
  const Scalar _tmp194 = _tmp137 * _tmp184 - _tmp191 * _tmp70 - _tmp192 * _tmp69;
  const Scalar _tmp195 = _tmp126 * _tmp184 - _tmp14 * _tmp194 - _tmp191 * _tmp84 - _tmp192 * _tmp83;
  const Scalar _tmp196 = _tmp13 * _tmp6;
  const Scalar _tmp197 = _tmp10 * _tmp3;
  const Scalar _tmp198 = _tmp196 * _tmp4 - _tmp197 * _tmp4;
  const Scalar _tmp199 = _tmp13 * _tmp27;
  const Scalar _tmp200 = _tmp3 * _tmp42;
  const Scalar _tmp201 = _tmp199 * _tmp4 - _tmp200 * _tmp4;
  const Scalar _tmp202 = _tmp21 * _tmp26;
  const Scalar _tmp203 = -_tmp197 * _tmp20 + _tmp58 * _tmp6;
  const Scalar _tmp204 =
      _tmp198 * _tmp62 - _tmp201 * _tmp202 - _tmp203 * _tmp31 + _tmp27 * _tmp58 - _tmp3 * _tmp60;
  const Scalar _tmp205 = _tmp22 * _tmp26;
  const Scalar _tmp206 = _tmp0 * _tmp44;
  const Scalar _tmp207 = -X_i(1, 0) * _tmp1 * _tmp13 + _tmp10 * _tmp206;
  const Scalar _tmp208 = -X_i(3, 0) * _tmp13 * _tmp5 + _tmp198 * _tmp48 - _tmp201 * _tmp205 +
                         _tmp206 * _tmp42 - _tmp207 * _tmp31;
  const Scalar _tmp209 = X_i(0, 1) * _tmp87;
  const Scalar _tmp210 = -_tmp203 * _tmp37 + _tmp204 * _tmp67 + _tmp207 - _tmp208 * _tmp57;
  const Scalar _tmp211 =
      _tmp13 * (_tmp198 * _tmp41 + _tmp204 * _tmp73 - _tmp208 * _tmp70 - _tmp210 * _tmp69);
  const Scalar _tmp212 = -X_i(0, 1) * _tmp211 + _tmp198 * _tmp82 + _tmp204 * _tmp80 -
                         _tmp208 * _tmp84 - _tmp209 * _tmp3 - _tmp210 * _tmp83 - _tmp93;
  const Scalar _tmp213 = _tmp208 * _tmp36;
  const Scalar _tmp214 = _tmp16 * _tmp26;
  const Scalar _tmp215 = _tmp13 * _tmp31;
  const Scalar _tmp216 = _tmp197 * _tmp31 - _tmp200;
  const Scalar _tmp217 =
      -_tmp128 * _tmp198 + _tmp199 + _tmp201 * _tmp214 - _tmp215 * _tmp6 + _tmp216;
  const Scalar _tmp218 = -_tmp197;
  const Scalar _tmp219 =
      -_tmp117 * _tmp203 + _tmp134 * _tmp204 + _tmp196 - _tmp217 * _tmp57 + _tmp218;
  const Scalar _tmp220 =
      _tmp13 * (_tmp137 * _tmp204 + _tmp138 * _tmp198 - _tmp217 * _tmp70 - _tmp219 * _tmp69);
  const Scalar _tmp221 = X_i(0, 1) * _tmp127;
  const Scalar _tmp222 =
      _tmp2 * (-X_i(0, 1) * _tmp220 - _tmp122 + _tmp126 * _tmp204 + _tmp133 * _tmp198 -
               _tmp217 * _tmp84 - _tmp219 * _tmp83 - _tmp221 * _tmp3);
  const Scalar _tmp223 = _tmp219 * _tmp26;
  const Scalar _tmp224 = _tmp30 * _tmp40;
  const Scalar _tmp225 = _tmp10 * _tmp224;
  const Scalar _tmp226 = _tmp42 * _tmp69;
  const Scalar _tmp227 = _tmp216 + _tmp22 * _tmp225 - _tmp22 * _tmp226;
  const Scalar _tmp228 = _tmp10 * _tmp41;
  const Scalar _tmp229 = -_tmp129 * _tmp20 + _tmp21 * _tmp225 - _tmp21 * _tmp226 + _tmp60;
  const Scalar _tmp230 = std::pow(_tmp4, Scalar(2));
  const Scalar _tmp231 = _tmp10 * _tmp230;
  const Scalar _tmp232 = -_tmp10 * _tmp85 + _tmp218 - _tmp227 * _tmp57 + _tmp229 * _tmp67;
  const Scalar _tmp233 = -_tmp227 * _tmp70 + _tmp229 * _tmp73 + _tmp231 * _tmp81 - _tmp232 * _tmp69;
  const Scalar _tmp234 = _tmp2 * (X_i(0, 2) * _tmp228 - _tmp14 * _tmp233 + _tmp209 -
                                  _tmp227 * _tmp84 + _tmp229 * _tmp80 - _tmp232 * _tmp83);
  const Scalar _tmp235 = _tmp232 * _tmp26;
  const Scalar _tmp236 = X_f(1, 2) * _tmp10;
  const Scalar _tmp237 = _tmp227 * _tmp36;
  const Scalar _tmp238 = std::pow(_tmp8, Scalar(-3));
  const Scalar _tmp239 = std::pow(_tmp7, Scalar(2));
  const Scalar _tmp240 =
      -_tmp129 - _tmp224 * _tmp238 * _tmp239 + _tmp238 * _tmp28 * _tmp69 * _tmp7 + _tmp42;
  const Scalar _tmp241 = -_tmp10 * _tmp120 + _tmp10 + _tmp134 * _tmp229 - _tmp240 * _tmp57;
  const Scalar _tmp242 =
      _tmp132 * _tmp231 + _tmp137 * _tmp229 - _tmp240 * _tmp70 - _tmp241 * _tmp69;
  const Scalar _tmp243 = _tmp10 * _tmp138;
  const Scalar _tmp244 = X_i(0, 2) * _tmp243 + _tmp126 * _tmp229 - _tmp14 * _tmp242 + _tmp221 -
                         _tmp240 * _tmp84 - _tmp241 * _tmp83;
  const Scalar _tmp245 = _tmp13 * _tmp224;
  const Scalar _tmp246 = -_tmp21 * _tmp245 + _tmp31 * _tmp58;
  const Scalar _tmp247 = -_tmp215 * _tmp3 - _tmp22 * _tmp245;
  const Scalar _tmp248 = _tmp13 * _tmp3;
  const Scalar _tmp249 = _tmp246 * _tmp67 - _tmp247 * _tmp57 + _tmp248 + _tmp37 * _tmp58;
  const Scalar _tmp250 = _tmp13 * _tmp41;
  const Scalar _tmp251 = _tmp13 * _tmp230;
  const Scalar _tmp252 = _tmp246 * _tmp73 - _tmp247 * _tmp70 - _tmp249 * _tmp69 - _tmp251 * _tmp81;
  const Scalar _tmp253 = -X_i(0, 2) * _tmp250 - _tmp14 * _tmp252 + _tmp246 * _tmp80 -
                         _tmp247 * _tmp84 - _tmp249 * _tmp83;
  const Scalar _tmp254 = _tmp247 * _tmp36;
  const Scalar _tmp255 = _tmp215 + _tmp225;
  const Scalar _tmp256 = -_tmp13;
  const Scalar _tmp257 = _tmp117 * _tmp58 + _tmp134 * _tmp246 - _tmp255 * _tmp57 + _tmp256;
  const Scalar _tmp258 =
      -_tmp132 * _tmp251 + _tmp137 * _tmp246 - _tmp255 * _tmp70 - _tmp257 * _tmp69;
  const Scalar _tmp259 = _tmp13 * _tmp138;
  const Scalar _tmp260 = _tmp255 * _tmp36;
  const Scalar _tmp261 = -X_i(0, 2) * _tmp259 - X_i(0, 3) * _tmp260 + _tmp126 * _tmp246 -
                         _tmp14 * _tmp258 - _tmp257 * _tmp83;
  const Scalar _tmp262 = _tmp257 * _tmp26;
  const Scalar _tmp263 = _tmp13 * _tmp69;
  const Scalar _tmp264 = _tmp22 * _tmp263 + _tmp248;
  const Scalar _tmp265 = _tmp21 * _tmp263 - _tmp58;
  const Scalar _tmp266 = -_tmp264 * _tmp57 + _tmp265 * _tmp67;
  const Scalar _tmp267 = -_tmp264 * _tmp70 + _tmp265 * _tmp73 - _tmp266 * _tmp69;
  const Scalar _tmp268 =
      _tmp2 * (-_tmp14 * _tmp267 - _tmp264 * _tmp84 + _tmp265 * _tmp80 - _tmp266 * _tmp83);
  const Scalar _tmp269 = _tmp26 * _tmp266;
  const Scalar _tmp270 = _tmp264 * _tmp36;
  const Scalar _tmp271 = -_tmp10 * _tmp69 + _tmp256;
  const Scalar _tmp272 = _tmp134 * _tmp265 - _tmp271 * _tmp57;
  const Scalar _tmp273 = _tmp137 * _tmp265 - _tmp271 * _tmp70 - _tmp272 * _tmp69;
  const Scalar _tmp274 = _tmp126 * _tmp265 - _tmp14 * _tmp273 - _tmp271 * _tmp84 - _tmp272 * _tmp83;
  const Scalar _tmp275 = -_tmp71;
  const Scalar _tmp276 = -_tmp205 * _tmp32 + std::pow(_tmp22, Scalar(2)) * _tmp47;
  const Scalar _tmp277 = -_tmp202 * _tmp32 + _tmp22 * _tmp62;
  const Scalar _tmp278 = -_tmp276 * _tmp57 + _tmp277 * _tmp67;
  const Scalar _tmp279 =
      _tmp22 * _tmp41 - _tmp276 * _tmp70 + _tmp277 * _tmp73 - _tmp278 * _tmp69 + _tmp3 * _tmp71;
  const Scalar _tmp280 = -_tmp14 * _tmp279 + _tmp22 * _tmp82 + _tmp275 - _tmp276 * _tmp84 +
                         _tmp277 * _tmp80 - _tmp278 * _tmp83;
  const Scalar _tmp281 = _tmp26 * _tmp278;
  const Scalar _tmp282 = _tmp276 * _tmp36;
  const Scalar _tmp283 = -_tmp16 * _tmp48;
  const Scalar _tmp284 = _tmp214 * _tmp32 + _tmp283;
  const Scalar _tmp285 = _tmp134 * _tmp277 - _tmp284 * _tmp57;
  const Scalar _tmp286 =
      _tmp119 * _tmp3 + _tmp137 * _tmp277 + _tmp138 * _tmp22 - _tmp284 * _tmp70 - _tmp285 * _tmp69;
  const Scalar _tmp287 = -_tmp119;
  const Scalar _tmp288 = _tmp126 * _tmp277 + _tmp133 * _tmp22 - _tmp14 * _tmp286 -
                         _tmp284 * _tmp84 - _tmp285 * _tmp83 + _tmp287;
  const Scalar _tmp289 = _tmp205 * _tmp29 + _tmp283;
  const Scalar _tmp290 = -_tmp16 * _tmp62 + _tmp202 * _tmp29;
  const Scalar _tmp291 = _tmp26 * (-_tmp289 * _tmp57 + _tmp290 * _tmp67);
  const Scalar _tmp292 =
      -_tmp24 * _tmp81 + _tmp275 - _tmp289 * _tmp70 + _tmp290 * _tmp73 - _tmp291 * _tmp4;
  const Scalar _tmp293 = -X_i(0, 2) * _tmp291 - _tmp14 * _tmp292 - _tmp16 * _tmp82 -
                         _tmp289 * _tmp84 + _tmp290 * _tmp80;
  const Scalar _tmp294 = _tmp289 * _tmp36;
  const Scalar _tmp295 = _tmp239 * _tmp47 * _tmp9 - _tmp26 * _tmp42 * _tmp7;
  const Scalar _tmp296 = _tmp134 * _tmp290 - _tmp295 * _tmp57;
  const Scalar _tmp297 =
      -_tmp132 * _tmp24 + _tmp137 * _tmp290 + _tmp287 - _tmp295 * _tmp70 - _tmp296 * _tmp69;
  const Scalar _tmp298 =
      _tmp126 * _tmp290 - _tmp133 * _tmp16 - _tmp14 * _tmp297 - _tmp295 * _tmp84 - _tmp296 * _tmp83;
  const Scalar _tmp299 = std::pow(_tmp21, Scalar(2));
  const Scalar _tmp300 = _tmp299 * _tmp47;
  const Scalar _tmp301 = _tmp300 * _tmp66 - _tmp48 * _tmp57;
  const Scalar _tmp302 = -_tmp301 * _tmp69 + _tmp41 - _tmp48 * _tmp70 + _tmp62 * _tmp73;
  const Scalar _tmp303 =
      -_tmp14 * _tmp302 - _tmp301 * _tmp83 - _tmp48 * _tmp84 + _tmp62 * _tmp80 + _tmp82;
  const Scalar _tmp304 = _tmp2 * _tmp303;
  const Scalar _tmp305 = _tmp36 * _tmp48;
  const Scalar _tmp306 = _tmp115 * _tmp300 + _tmp128 * _tmp57;
  const Scalar _tmp307 = _tmp128 * _tmp70 + _tmp137 * _tmp62 + _tmp138 - _tmp306 * _tmp69;
  const Scalar _tmp308 =
      _tmp126 * _tmp62 + _tmp128 * _tmp84 + _tmp133 - _tmp14 * _tmp307 - _tmp306 * _tmp83;
  const Scalar _tmp309 = _tmp26 * _tmp299;
  const Scalar _tmp310 = _tmp205 * _tmp57 - _tmp309 * _tmp66;
  const Scalar _tmp311 = _tmp26 * _tmp310;
  const Scalar _tmp312 = -_tmp202 * _tmp73 + _tmp205 * _tmp70 - _tmp310 * _tmp69;
  const Scalar _tmp313 = -_tmp14 * _tmp312 - _tmp202 * _tmp80 + _tmp205 * _tmp84 - _tmp310 * _tmp83;
  const Scalar _tmp314 = _tmp205 * _tmp36;
  const Scalar _tmp315 = -_tmp115 * _tmp309 - _tmp214 * _tmp57;
  const Scalar _tmp316 = -_tmp137 * _tmp202 - _tmp214 * _tmp70 - _tmp315 * _tmp69;
  const Scalar _tmp317 =
      -_tmp126 * _tmp202 - _tmp14 * _tmp316 - _tmp214 * _tmp84 - _tmp315 * _tmp83;
  const Scalar _tmp318 = _tmp26 * _tmp315;
  const Scalar _tmp319 = std::pow(_tmp33, Scalar(2)) * _tmp65;
  const Scalar _tmp320 = _tmp26 * (_tmp21 * _tmp319 - _tmp22 * _tmp37);
  const Scalar _tmp321 = _tmp20 * _tmp319 + _tmp3 * _tmp37 - _tmp320 * _tmp4;
  const Scalar _tmp322 = -_tmp37;
  const Scalar _tmp323 = -X_i(0, 2) * _tmp320 + X_i(0, 3) * _tmp319 - _tmp14 * _tmp321 + _tmp322;
  const Scalar _tmp324 = _tmp114 * _tmp73;
  const Scalar _tmp325 = _tmp114 * _tmp67;
  const Scalar _tmp326 = -_tmp117 * _tmp22 + _tmp325;
  const Scalar _tmp327 = _tmp117 * _tmp3 + _tmp324 - _tmp326 * _tmp69;
  const Scalar _tmp328 = -_tmp114 * _tmp77;
  const Scalar _tmp329 = -_tmp117;
  const Scalar _tmp330 = _tmp114 * _tmp80;
  const Scalar _tmp331 = _tmp26 * _tmp326;
  const Scalar _tmp332 = -X_i(0, 2) * _tmp331 - _tmp14 * _tmp327 + _tmp329 + _tmp330;
  const Scalar _tmp333 = -_tmp114 * _tmp99;
  const Scalar _tmp334 = _tmp16 * _tmp37 + _tmp325;
  const Scalar _tmp335 = _tmp322 + _tmp324 - _tmp334 * _tmp69;
  const Scalar _tmp336 = -_tmp14 * _tmp335 + _tmp330 - _tmp334 * _tmp83;
  const Scalar _tmp337 = _tmp26 * _tmp334;
  const Scalar _tmp338 = std::pow(_tmp114, Scalar(2));
  const Scalar _tmp339 = _tmp338 * _tmp65;
  const Scalar _tmp340 = _tmp117 * _tmp16 + _tmp21 * _tmp339;
  const Scalar _tmp341 = _tmp26 * _tmp340;
  const Scalar _tmp342 = _tmp136 * _tmp338 + _tmp329 - _tmp340 * _tmp69;
  const Scalar _tmp343 = X_i(0, 3) * _tmp339 - _tmp14 * _tmp342 - _tmp340 * _tmp83;
  const Scalar _tmp344 = _tmp322 - _tmp34 * _tmp66;
  const Scalar _tmp345 = -_tmp31 * _tmp73 - _tmp344 * _tmp69;
  const Scalar _tmp346 = _tmp13 * _tmp345;
  const Scalar _tmp347 = -_tmp14 * _tmp345 - _tmp31 * _tmp80 - _tmp344 * _tmp83;
  const Scalar _tmp348 = -_tmp115 * _tmp34 + _tmp329;
  const Scalar _tmp349 = -_tmp137 * _tmp31 - _tmp348 * _tmp69;
  const Scalar _tmp350 = -_tmp126 * _tmp31 - _tmp14 * _tmp349 - _tmp348 * _tmp83;
  const Scalar _tmp351 = -_tmp67 * _tmp69 + _tmp73;
  const Scalar _tmp352 = -_tmp14 * _tmp351 - _tmp67 * _tmp83 + _tmp80;
  const Scalar _tmp353 = -_tmp134 * _tmp69 + _tmp137;
  const Scalar _tmp354 = _tmp126 - _tmp134 * _tmp83 - _tmp14 * _tmp353;

  // Output terms (1)
  Eigen::Matrix<Scalar, 6, 16> _res;

  _res(0, 0) = -X_f(0, 0) * _tmp94 + X_f(0, 3) * _tmp79 - _tmp18 * _tmp92 - _tmp61 * _tmp95 -
               _tmp64 * _tmp77 + _tmp68 * _tmp78 + _tmp75 * _tmp76 + _tmp90 * _tmp91;
  _res(1, 0) = -X_f(1, 0) * _tmp94 + X_f(1, 3) * _tmp79 + _tmp100 * _tmp90 - _tmp101 * _tmp61 -
               _tmp18 * _tmp96 - _tmp64 * _tmp99 + _tmp68 * _tmp98 + _tmp75 * _tmp97;
  _res(2, 0) = -X_f(2, 0) * _tmp94 + X_f(2, 3) * _tmp79 - _tmp102 * _tmp18 + _tmp103 * _tmp75 +
               _tmp104 * _tmp68 - _tmp105 * _tmp64 + _tmp106 * _tmp90 - _tmp107 * _tmp61;
  _res(3, 0) = -X_f(3, 0) * _tmp94 + X_f(3, 3) * _tmp79 - _tmp108 * _tmp18 + _tmp109 * _tmp75 -
               _tmp110 * _tmp64 + _tmp111 * _tmp68 + _tmp112 * _tmp90 - _tmp113 * _tmp61;
  _res(4, 0) = -X_f(0, 0) * _tmp125 + X_f(0, 3) * _tmp131 - _tmp116 * _tmp64 + _tmp135 * _tmp78 +
               _tmp139 * _tmp76 + _tmp140 * _tmp91 - _tmp141 * _tmp18 - _tmp142 * _tmp61;
  _res(5, 0) = -X_f(1, 0) * _tmp125 + X_f(1, 3) * _tmp131 + _tmp100 * _tmp140 + _tmp135 * _tmp98 +
               _tmp139 * _tmp97 - _tmp143 * _tmp61 - _tmp144 * _tmp64 - _tmp145 * _tmp18;
  _res(0, 1) = _tmp146 * _tmp95 - _tmp148 * _tmp92 + _tmp152 * _tmp153 - _tmp155 * _tmp77 +
               _tmp156 * _tmp78 + _tmp159 * _tmp76 + _tmp160 * _tmp91;
  _res(1, 1) = _tmp100 * _tmp160 + _tmp101 * _tmp146 - _tmp148 * _tmp96 + _tmp152 * _tmp161 -
               _tmp155 * _tmp99 + _tmp156 * _tmp98 + _tmp159 * _tmp97;
  _res(2, 1) = X_f(2, 3) * _tmp162 - _tmp102 * _tmp148 + _tmp103 * _tmp159 + _tmp104 * _tmp156 -
               _tmp105 * _tmp155 + _tmp106 * _tmp160 + _tmp107 * _tmp146;
  _res(3, 1) = X_f(3, 3) * _tmp162 - _tmp108 * _tmp148 + _tmp109 * _tmp159 - _tmp110 * _tmp155 +
               _tmp111 * _tmp156 + _tmp112 * _tmp160 + _tmp113 * _tmp146;
  _res(4, 1) = X_f(0, 3) * _tmp164 - _tmp116 * _tmp155 - _tmp141 * _tmp148 + _tmp142 * _tmp146 +
               _tmp165 * _tmp78 + _tmp166 * _tmp76 + _tmp167 * _tmp91;
  _res(5, 1) = X_f(1, 3) * _tmp164 + _tmp100 * _tmp167 + _tmp143 * _tmp146 - _tmp144 * _tmp155 -
               _tmp145 * _tmp148 + _tmp165 * _tmp98 + _tmp166 * _tmp97;
  _res(0, 2) = X_f(0, 0) * _tmp176 + _tmp153 * _tmp173 - _tmp170 * _tmp92 - _tmp171 * _tmp77 +
               _tmp174 * _tmp78 + _tmp175 * _tmp76;
  _res(1, 2) = X_f(1, 0) * _tmp176 + _tmp161 * _tmp173 - _tmp170 * _tmp96 - _tmp171 * _tmp99 +
               _tmp174 * _tmp98 + _tmp175 * _tmp97;
  _res(2, 2) = X_f(2, 0) * _tmp176 + X_f(2, 3) * _tmp177 - _tmp102 * _tmp170 + _tmp103 * _tmp175 +
               _tmp104 * _tmp174 - _tmp105 * _tmp171;
  _res(3, 2) = X_f(3, 0) * _tmp176 + X_f(3, 3) * _tmp177 - _tmp108 * _tmp170 + _tmp109 * _tmp175 -
               _tmp110 * _tmp171 + _tmp111 * _tmp174;
  _res(4, 2) = X_f(0, 2) * _tmp182 - _tmp116 * _tmp171 - _tmp141 * _tmp170 + _tmp153 * _tmp178 +
               _tmp180 * _tmp76 + _tmp181 * _tmp91;
  _res(5, 2) = X_f(1, 2) * _tmp182 + _tmp100 * _tmp181 - _tmp144 * _tmp171 - _tmp145 * _tmp170 +
               _tmp161 * _tmp178 + _tmp180 * _tmp97;
  _res(0, 3) = X_f(0, 2) * _tmp188 + X_f(0, 3) * _tmp190 - _tmp184 * _tmp77 + _tmp187 * _tmp76 +
               _tmp189 * _tmp91;
  _res(1, 3) = X_f(1, 2) * _tmp188 + X_f(1, 3) * _tmp190 + _tmp100 * _tmp189 - _tmp184 * _tmp99 +
               _tmp187 * _tmp97;
  _res(2, 3) = X_f(2, 2) * _tmp188 + X_f(2, 3) * _tmp190 + _tmp103 * _tmp187 - _tmp105 * _tmp184 +
               _tmp106 * _tmp189;
  _res(3, 3) = X_f(3, 2) * _tmp188 + X_f(3, 3) * _tmp190 + _tmp109 * _tmp187 - _tmp110 * _tmp184 +
               _tmp112 * _tmp189;
  _res(4, 3) = X_f(0, 3) * _tmp193 - _tmp116 * _tmp184 + _tmp192 * _tmp78 + _tmp194 * _tmp76 +
               _tmp195 * _tmp91;
  _res(5, 3) = X_f(1, 3) * _tmp193 + _tmp100 * _tmp195 - _tmp144 * _tmp184 + _tmp192 * _tmp98 +
               _tmp194 * _tmp97;
  _res(0, 4) = X_f(0, 1) * _tmp211 + _tmp153 * _tmp208 - _tmp198 * _tmp92 - _tmp204 * _tmp77 +
               _tmp210 * _tmp78 + _tmp212 * _tmp91 + _tmp3 * _tmp95;
  _res(1, 4) = X_f(1, 1) * _tmp211 + _tmp100 * _tmp212 + _tmp101 * _tmp3 + _tmp161 * _tmp208 -
               _tmp198 * _tmp96 - _tmp204 * _tmp99 + _tmp210 * _tmp98;
  _res(2, 4) = X_f(2, 1) * _tmp211 + X_f(2, 3) * _tmp213 - _tmp102 * _tmp198 + _tmp104 * _tmp210 -
               _tmp105 * _tmp204 + _tmp106 * _tmp212 + _tmp107 * _tmp3;
  _res(3, 4) = X_f(3, 1) * _tmp211 + X_f(3, 3) * _tmp213 - _tmp108 * _tmp198 - _tmp110 * _tmp204 +
               _tmp111 * _tmp210 + _tmp112 * _tmp212 + _tmp113 * _tmp3;
  _res(4, 4) = X_f(0, 0) * _tmp222 + X_f(0, 1) * _tmp220 + X_f(0, 2) * _tmp223 - _tmp116 * _tmp204 -
               _tmp141 * _tmp198 + _tmp142 * _tmp3 + _tmp153 * _tmp217;
  _res(5, 4) = X_f(1, 0) * _tmp222 + X_f(1, 1) * _tmp220 + X_f(1, 2) * _tmp223 + _tmp143 * _tmp3 -
               _tmp144 * _tmp204 - _tmp145 * _tmp198 + _tmp161 * _tmp217;
  _res(0, 5) = X_f(0, 0) * _tmp234 - X_f(0, 2) * _tmp228 + X_f(0, 2) * _tmp235 + _tmp153 * _tmp227 -
               _tmp229 * _tmp77 + _tmp233 * _tmp76 - _tmp95;
  _res(1, 5) = X_f(1, 0) * _tmp234 + X_f(1, 2) * _tmp235 - _tmp101 + _tmp161 * _tmp227 -
               _tmp229 * _tmp99 + _tmp233 * _tmp97 - _tmp236 * _tmp41;
  _res(2, 5) = X_f(2, 0) * _tmp234 - X_f(2, 2) * _tmp228 + X_f(2, 2) * _tmp235 +
               X_f(2, 3) * _tmp237 + _tmp103 * _tmp233 - _tmp105 * _tmp229 - _tmp107;
  _res(3, 5) = X_f(3, 0) * _tmp234 - X_f(3, 2) * _tmp228 + X_f(3, 2) * _tmp235 +
               X_f(3, 3) * _tmp237 + _tmp109 * _tmp233 - _tmp110 * _tmp229 - _tmp113;
  _res(4, 5) = -X_f(0, 2) * _tmp243 - _tmp116 * _tmp229 - _tmp142 + _tmp153 * _tmp240 +
               _tmp241 * _tmp78 + _tmp242 * _tmp76 + _tmp244 * _tmp91;
  _res(5, 5) = _tmp100 * _tmp244 - _tmp138 * _tmp236 - _tmp143 - _tmp144 * _tmp229 +
               _tmp161 * _tmp240 + _tmp241 * _tmp98 + _tmp242 * _tmp97;
  _res(0, 6) = X_f(0, 2) * _tmp250 + _tmp153 * _tmp247 - _tmp246 * _tmp77 + _tmp249 * _tmp78 +
               _tmp252 * _tmp76 + _tmp253 * _tmp91;
  _res(1, 6) = X_f(1, 2) * _tmp250 + _tmp100 * _tmp253 + _tmp161 * _tmp247 - _tmp246 * _tmp99 +
               _tmp249 * _tmp98 + _tmp252 * _tmp97;
  _res(2, 6) = X_f(2, 2) * _tmp250 + X_f(2, 3) * _tmp254 + _tmp103 * _tmp252 + _tmp104 * _tmp249 -
               _tmp105 * _tmp246 + _tmp106 * _tmp253;
  _res(3, 6) = X_f(3, 2) * _tmp250 + X_f(3, 3) * _tmp254 + _tmp109 * _tmp252 - _tmp110 * _tmp246 +
               _tmp111 * _tmp249 + _tmp112 * _tmp253;
  _res(4, 6) = X_f(0, 2) * _tmp259 + X_f(0, 2) * _tmp262 + X_f(0, 3) * _tmp260 - _tmp116 * _tmp246 +
               _tmp258 * _tmp76 + _tmp261 * _tmp91;
  _res(5, 6) = X_f(1, 2) * _tmp259 + X_f(1, 2) * _tmp262 + X_f(1, 3) * _tmp260 + _tmp100 * _tmp261 -
               _tmp144 * _tmp246 + _tmp258 * _tmp97;
  _res(0, 7) = X_f(0, 0) * _tmp268 + X_f(0, 2) * _tmp269 + _tmp153 * _tmp264 - _tmp265 * _tmp77 +
               _tmp267 * _tmp76;
  _res(1, 7) = X_f(1, 0) * _tmp268 + X_f(1, 2) * _tmp269 + _tmp161 * _tmp264 - _tmp265 * _tmp99 +
               _tmp267 * _tmp97;
  _res(2, 7) = X_f(2, 0) * _tmp268 + X_f(2, 2) * _tmp269 + X_f(2, 3) * _tmp270 + _tmp103 * _tmp267 -
               _tmp105 * _tmp265;
  _res(3, 7) = X_f(3, 0) * _tmp268 + X_f(3, 2) * _tmp269 + X_f(3, 3) * _tmp270 + _tmp109 * _tmp267 -
               _tmp110 * _tmp265;
  _res(4, 7) = -_tmp116 * _tmp265 + _tmp153 * _tmp271 + _tmp272 * _tmp78 + _tmp273 * _tmp76 +
               _tmp274 * _tmp91;
  _res(5, 7) = _tmp100 * _tmp274 - _tmp144 * _tmp265 + _tmp161 * _tmp271 + _tmp272 * _tmp98 +
               _tmp273 * _tmp97;
  _res(0, 8) = X_f(0, 2) * _tmp281 + _tmp153 * _tmp276 - _tmp22 * _tmp92 - _tmp277 * _tmp77 +
               _tmp279 * _tmp76 + _tmp280 * _tmp91;
  _res(1, 8) = X_f(1, 2) * _tmp281 + _tmp100 * _tmp280 + _tmp161 * _tmp276 - _tmp22 * _tmp96 -
               _tmp277 * _tmp99 + _tmp279 * _tmp97;
  _res(2, 8) = X_f(2, 2) * _tmp281 + X_f(2, 3) * _tmp282 - _tmp102 * _tmp22 + _tmp103 * _tmp279 -
               _tmp105 * _tmp277 + _tmp106 * _tmp280;
  _res(3, 8) = X_f(3, 2) * _tmp281 + X_f(3, 3) * _tmp282 - _tmp108 * _tmp22 + _tmp109 * _tmp279 -
               _tmp110 * _tmp277 + _tmp112 * _tmp280;
  _res(4, 8) = -_tmp116 * _tmp277 - _tmp141 * _tmp22 + _tmp153 * _tmp284 + _tmp285 * _tmp78 +
               _tmp286 * _tmp76 + _tmp288 * _tmp91;
  _res(5, 8) = _tmp100 * _tmp288 - _tmp144 * _tmp277 - _tmp145 * _tmp22 + _tmp161 * _tmp284 +
               _tmp285 * _tmp98 + _tmp286 * _tmp97;
  _res(0, 9) = X_f(0, 2) * _tmp291 + _tmp153 * _tmp289 + _tmp16 * _tmp92 - _tmp290 * _tmp77 +
               _tmp292 * _tmp76 + _tmp293 * _tmp91;
  _res(1, 9) = X_f(1, 2) * _tmp291 + _tmp100 * _tmp293 + _tmp16 * _tmp96 + _tmp161 * _tmp289 -
               _tmp290 * _tmp99 + _tmp292 * _tmp97;
  _res(2, 9) = X_f(2, 2) * _tmp291 + X_f(2, 3) * _tmp294 + _tmp102 * _tmp16 + _tmp103 * _tmp292 -
               _tmp105 * _tmp290 + _tmp106 * _tmp293;
  _res(3, 9) = X_f(3, 2) * _tmp291 + X_f(3, 3) * _tmp294 + _tmp108 * _tmp16 + _tmp109 * _tmp292 -
               _tmp110 * _tmp290 + _tmp112 * _tmp293;
  _res(4, 9) = -_tmp116 * _tmp290 + _tmp141 * _tmp16 + _tmp153 * _tmp295 + _tmp296 * _tmp78 +
               _tmp297 * _tmp76 + _tmp298 * _tmp91;
  _res(5, 9) = _tmp100 * _tmp298 - _tmp144 * _tmp290 + _tmp145 * _tmp16 + _tmp161 * _tmp295 +
               _tmp296 * _tmp98 + _tmp297 * _tmp97;
  _res(0, 10) = _tmp153 * _tmp48 + _tmp301 * _tmp78 + _tmp302 * _tmp76 + _tmp303 * _tmp91 -
                _tmp62 * _tmp77 - _tmp92;
  _res(1, 10) = _tmp100 * _tmp303 + _tmp161 * _tmp48 + _tmp301 * _tmp98 + _tmp302 * _tmp97 -
                _tmp62 * _tmp99 - _tmp96;
  _res(2, 10) = X_f(2, 0) * _tmp304 + X_f(2, 3) * _tmp305 - _tmp102 + _tmp103 * _tmp302 +
                _tmp104 * _tmp301 - _tmp105 * _tmp62;
  _res(3, 10) = X_f(3, 0) * _tmp304 + X_f(3, 3) * _tmp305 - _tmp108 + _tmp109 * _tmp302 -
                _tmp110 * _tmp62 + _tmp111 * _tmp301;
  _res(4, 10) = -_tmp116 * _tmp62 - _tmp128 * _tmp153 - _tmp141 + _tmp306 * _tmp78 +
                _tmp307 * _tmp76 + _tmp308 * _tmp91;
  _res(5, 10) = _tmp100 * _tmp308 - _tmp128 * _tmp161 - _tmp144 * _tmp62 - _tmp145 +
                _tmp306 * _tmp98 + _tmp307 * _tmp97;
  _res(0, 11) = X_f(0, 2) * _tmp311 - _tmp153 * _tmp205 + _tmp202 * _tmp77 + _tmp312 * _tmp76 +
                _tmp313 * _tmp91;
  _res(1, 11) = X_f(1, 2) * _tmp311 + _tmp100 * _tmp313 - _tmp161 * _tmp205 + _tmp202 * _tmp99 +
                _tmp312 * _tmp97;
  _res(2, 11) = X_f(2, 2) * _tmp311 - X_f(2, 3) * _tmp314 + _tmp103 * _tmp312 + _tmp105 * _tmp202 +
                _tmp106 * _tmp313;
  _res(3, 11) = X_f(3, 2) * _tmp311 - X_f(3, 3) * _tmp314 + _tmp109 * _tmp312 + _tmp110 * _tmp202 +
                _tmp112 * _tmp313;
  _res(4, 11) = X_f(0, 2) * _tmp318 + _tmp116 * _tmp202 + _tmp153 * _tmp214 + _tmp316 * _tmp76 +
                _tmp317 * _tmp91;
  _res(5, 11) = X_f(1, 2) * _tmp318 + _tmp100 * _tmp317 + _tmp144 * _tmp202 + _tmp161 * _tmp214 +
                _tmp316 * _tmp97;
  _res(0, 12) = X_f(0, 2) * _tmp320 - X_f(0, 3) * _tmp319 + _tmp321 * _tmp76 + _tmp323 * _tmp91;
  _res(1, 12) = X_f(1, 2) * _tmp320 - X_f(1, 3) * _tmp319 + _tmp100 * _tmp323 + _tmp321 * _tmp97;
  _res(2, 12) = X_f(2, 2) * _tmp320 - X_f(2, 3) * _tmp319 + _tmp103 * _tmp321 + _tmp106 * _tmp323;
  _res(3, 12) = X_f(3, 2) * _tmp320 - X_f(3, 3) * _tmp319 + _tmp109 * _tmp321 + _tmp112 * _tmp323;
  _res(4, 12) = X_f(0, 2) * _tmp331 + _tmp327 * _tmp76 + _tmp328 + _tmp332 * _tmp91;
  _res(5, 12) = X_f(1, 2) * _tmp331 + _tmp100 * _tmp332 + _tmp327 * _tmp97 + _tmp333;
  _res(0, 13) = X_f(0, 2) * _tmp337 + _tmp328 + _tmp335 * _tmp76 + _tmp336 * _tmp91;
  _res(1, 13) = X_f(1, 2) * _tmp337 + _tmp100 * _tmp336 + _tmp333 + _tmp335 * _tmp97;
  _res(2, 13) = X_f(2, 2) * _tmp337 + _tmp103 * _tmp335 - _tmp105 * _tmp114 + _tmp106 * _tmp336;
  _res(3, 13) = X_f(3, 2) * _tmp337 + _tmp109 * _tmp335 - _tmp110 * _tmp114 + _tmp112 * _tmp336;
  _res(4, 13) = X_f(0, 2) * _tmp341 - X_f(0, 3) * _tmp339 + _tmp342 * _tmp76 + _tmp343 * _tmp91;
  _res(5, 13) = X_f(1, 2) * _tmp341 - X_f(1, 3) * _tmp339 + _tmp100 * _tmp343 + _tmp342 * _tmp97;
  _res(0, 14) = X_f(0, 1) * _tmp346 + _tmp31 * _tmp77 + _tmp344 * _tmp78 + _tmp347 * _tmp91;
  _res(1, 14) = X_f(1, 1) * _tmp346 + _tmp100 * _tmp347 + _tmp31 * _tmp99 + _tmp344 * _tmp98;
  _res(2, 14) = X_f(2, 1) * _tmp346 + _tmp104 * _tmp344 + _tmp105 * _tmp31 + _tmp106 * _tmp347;
  _res(3, 14) = X_f(3, 1) * _tmp346 + _tmp110 * _tmp31 + _tmp111 * _tmp344 + _tmp112 * _tmp347;
  _res(4, 14) = _tmp116 * _tmp31 + _tmp348 * _tmp78 + _tmp349 * _tmp76 + _tmp350 * _tmp91;
  _res(5, 14) = _tmp100 * _tmp350 + _tmp144 * _tmp31 + _tmp348 * _tmp98 + _tmp349 * _tmp97;
  _res(0, 15) = _tmp351 * _tmp76 + _tmp352 * _tmp91 + _tmp67 * _tmp78 - _tmp77;
  _res(1, 15) = _tmp100 * _tmp352 + _tmp351 * _tmp97 + _tmp67 * _tmp98 - _tmp99;
  _res(2, 15) = _tmp103 * _tmp351 + _tmp104 * _tmp67 - _tmp105 + _tmp106 * _tmp352;
  _res(3, 15) = _tmp109 * _tmp351 - _tmp110 + _tmp111 * _tmp67 + _tmp112 * _tmp352;
  _res(4, 15) = -_tmp116 + _tmp134 * _tmp78 + _tmp353 * _tmp76 + _tmp354 * _tmp91;
  _res(5, 15) = _tmp100 * _tmp354 + _tmp134 * _tmp98 - _tmp144 + _tmp353 * _tmp97;

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
